version: '3.8'

services:
  clean-flask-app:
    build: .
    container_name: clean-flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}  # Provide in `.env`
    env_file:
      - .env
    restart: unless-stopped
